### ISSUE TITLE
Output l3v2 when needed and/or by default

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/antimony#55]
When l3v2-only elements 'max' 'min' and others are used, Antimony should output l3v2 models.  It might be easiest to just always output l3v2 models.

**Comment by eltix** [comment]
@luciansmith Great idea! Is there any way to currently write to L3V2? `exportToSBML()` writes L3V1 and the function has no argument to select the version.

**Comment by luciansmith** [comment]
https://github.com/sys-bio/antimony/pull/79 now makes l3v2 the default; if anyone wants to use the binaries before the next release; they're at https://dev.azure.com/TheRoadrunnerProject/Antimony/_build/results?buildId=2105&view=artifacts&pathAsName=false&type=publishedArtifacts

@eltix : If antimony exports to l3v2 by default, is that sufficient?  If you needed an L3v1 version, would you be comfortable using libsbml directly to do so?

**Comment by eltix** [comment]
@luciansmith Thank you for this. Yes that is sufficient, we do not need to write to any other version than L3V2

**Comment by luciansmith** [comment]
(L3v2 now the default in actual released code; just never closed the issue.)
